// C:\workspace\Stella AI Studio\src\PluginExporter.cpp

#include "PluginExporter.h"
#include "WasmCompiler.h"

#include "StellaRuntimeData.h"
#include "StellaToolchainPaths.h"

namespace
{
    juce::File compilerIn (const juce::File& toolchain)
    {
       #if JUCE_WINDOWS
        return toolchain.getChildFile ("bin").getChildFile ("x86_64-w64-mingw32-clang++.exe");
       #else
        return toolchain.getChildFile ("bin").getChildFile ("x86_64-w64-mingw32-clang++");
       #endif
    }

    /** A C++ string literal for any text. */
    juce::String literal (const juce::String& text)
    {
        juce::String result ("\"");

        for (auto c : text)
        {
            if (c == '"' || c == '\\')
                result << '\\' << juce::String::charToString (c);
            else if (c >= 32 && c < 127)
                result << juce::String::charToString (c);
        }

        return result + "\"";
    }

    juce::File besideProgram (const juce::String& name)
    {
        return juce::File::getSpecialLocation (juce::File::currentExecutableFile).getParentDirectory().getChildFile (name);
    }

    juce::String literalOrNull (const juce::String& text)
    {
        return text.isNotEmpty() ? literal (text) : juce::String ("nullptr");
    }

    /** Bytes as a C++ array body, 24 to a line. */
    void appendBytes (juce::MemoryOutputStream& out, const juce::MemoryBlock& data)
    {
        static const char* const hex = "0123456789abcdef";
        const auto* bytes = static_cast<const juce::uint8*> (data.getData());
        char line[24 * 5 + 2];

        for (size_t i = 0; i < data.getSize(); i += 24)
        {
            auto* c = line;

            for (size_t j = i; j < std::min (data.getSize(), i + 24); ++j)
            {
                *c++ = '0'; *c++ = 'x';
                *c++ = hex[bytes[j] >> 4];
                *c++ = hex[bytes[j] & 15];
                *c++ = ',';
            }

            *c++ = '\n';
            out.write (line, (size_t) (c - line));
        }

        if (data.getSize() == 0)
            out << "0\n";
    }

    juce::MemoryBlock png (const juce::Image& image)
    {
        juce::MemoryOutputStream out;
        juce::PNGImageFormat().writeImageToStream (image, out);
        return out.getMemoryBlock();
    }

    juce::String guiSource (const PluginExporter::Gui& gui)
    {
        juce::MemoryOutputStream out;
        out << "// Generated by Stella AI Studio for this export: the plugin's GUI, baked.\n\n"
            << "#include \"stella_gui.h\"\n\nnamespace stella::gui\n{\n";

        out << "    extern const int width = " << gui.width << ", height = " << gui.height << ";\n\n";
        out << "    extern const unsigned char backgroundPng[] =\n    {\n";
        appendBytes (out, gui.background);
        out << "    };\n\n    extern const int backgroundPngSize = " << (int) gui.background.getSize() << ";\n\n";

        for (size_t i = 0; i < gui.strips.size(); ++i)
        {
            out << "    static const unsigned char strip" << (int) i << "[] =\n    {\n";
            appendBytes (out, gui.strips[i].png);
            out << "    };\n\n";
        }

        out << "    extern const Strip strips[] =\n    {\n";

        for (size_t i = 0; i < gui.strips.size(); ++i)
            out << "        { strip" << (int) i << ", " << (int) gui.strips[i].png.getSize() << ", " << gui.strips[i].frameWidth << ", "
                << gui.strips[i].frameHeight << ", " << gui.strips[i].frames << " },\n";

        if (gui.strips.empty())
            out << "        { nullptr, 0, 0, 0, 0 },\n";

        out << "    };\n\n    extern const int numStrips = " << (int) gui.strips.size() << ";\n\n";

        out << "    extern const Widget widgets[] =\n    {\n" << gui.widgetRows;

        if (gui.numWidgets == 0)
            out << "        { Kind::knob, 0, 0, 0, 0, -1, nullptr, nullptr, nullptr, nullptr, nullptr, 0, 0, 0, 0.0f, 0, 0, 0.0f },\n";

        out << "    };\n\n    extern const int numWidgets = " << gui.numWidgets << ";\n\n";

        out << gui.presetArrays << "    extern const Preset presets[] =\n    {\n" << gui.presetRows;

        if (gui.numPresets == 0)
            out << "        { nullptr, 0 },\n";

        out << "    };\n\n    extern const int numPresets = " << gui.numPresets << ";\n}\n";
        return out.toString();
    }
}

//==============================================================================
PluginExporter::Gui PluginExporter::prepareGui (const GuiLayout& layout, const PluginCanvas::Bake& bake,
                                                const std::map<juce::String, juce::String>& unitsById, const juce::StringArray& displayIds,
                                                const std::vector<Preset>& presets)
{
    Gui gui;

    // The presets go in even without a GUI (a later plugin GUI, or the host's, can use them).
    for (size_t i = 0; i < presets.size(); ++i)
    {
        gui.presetArrays << "    static const PresetValue preset" << (int) i << "[] =\n    {\n";

        for (const auto& [id, value] : presets[i].values)
            gui.presetArrays << "        { " << literal (id) << ", " << juce::String (value, 6) << "f },\n";

        if (presets[i].values.empty())
            gui.presetArrays << "        { nullptr, 0.0f },\n";

        gui.presetArrays << "    };\n\n";
        gui.presetRows << "        { preset" << (int) i << ", " << (int) presets[i].values.size() << " },\n";
        ++gui.numPresets;
    }

    if (layout.widgets.empty() || ! bake.background.isValid())
        return gui;

    gui.width = layout.width;
    gui.height = layout.height;
    gui.background = png (bake.background);

    for (const auto& strip : bake.strips)
        gui.strips.push_back ({ png (strip.image), strip.frameWidth, strip.frameHeight, strip.frames });

    auto role = [] (const GuiWidget& w, const char* name)
    {
        const auto found = w.roles.find (name);
        return found != w.roles.end() ? found->second : juce::String();
    };

    for (size_t i = 0; i < layout.widgets.size() && i < bake.movingArea.size(); ++i)
    {
        const auto& w = layout.widgets[i];
        const auto area = bake.movingArea[i];
        const auto strip = i < bake.stripOf.size() ? bake.stripOf[i] : -1;
        const char* kind = nullptr;
        juce::String p1, p2, p3, p4, source;

        switch (w.type)
        {
            case GuiWidget::Type::knob:      kind = "knob";     p1 = w.param; break;
            case GuiWidget::Type::slider:    kind = "slider";   p1 = w.param; break;
            case GuiWidget::Type::toggle:    kind = "toggle";   p1 = w.param; break;
            case GuiWidget::Type::selector:  kind = "selector"; p1 = w.param; break;
            case GuiWidget::Type::xy:        kind = "xy";       p1 = role (w, "x"); p2 = role (w, "y"); break;
            case GuiWidget::Type::meter:     kind = "meter";    source = w.source; break;
            case GuiWidget::Type::lamp:      kind = "lamp";     source = w.source; break;
            case GuiWidget::Type::scope:     kind = "scope";    source = w.source; break;
            case GuiWidget::Type::envelope:  kind = "envelope"; p1 = role (w, "attack"); p2 = role (w, "decay"); p3 = role (w, "sustain"); p4 = role (w, "release"); break;
            case GuiWidget::Type::filter:    kind = "filter";   p1 = role (w, "cutoff"); p2 = role (w, "resonance"); break;
            case GuiWidget::Type::preset:    kind = "preset"; break;
            case GuiWidget::Type::keyboard:  kind = "keyboard"; break;
            // Still things: in the background, unless they lie in front of something that
            // moves; then a layer of their own (one frame), drawn over it.
            case GuiWidget::Type::image:
            case GuiWidget::Type::label:
            case GuiWidget::Type::group:
            case GuiWidget::Type::shape:     kind = strip >= 0 ? "picture" : nullptr; break;
        }

        if (kind == nullptr || area.isEmpty())
            continue;

        const auto colour = (w.colour.isTransparent() ? juce::Colour (0xffe5484d) : w.colour).getARGB();
        const auto vertical = w.type == GuiWidget::Type::slider ? (w.vertical ? 1 : 0) : (area.getHeight() >= area.getWidth() ? 1 : 0);
        // A keyboard's range: its lowest key in mode, its highest in count.
        const auto count = w.type == GuiWidget::Type::keyboard ? w.highNote
                         : strip >= 0 && (w.type == GuiWidget::Type::selector || w.type == GuiWidget::Type::preset) ? bake.strips[(size_t) strip].frames : 0;

        int mode = 0;

        if (w.type == GuiWidget::Type::keyboard)
            mode = w.lowNote;
        else if (w.type == GuiWidget::Type::meter)
            mode = w.mode == "rms" ? 1 : 0;
        else if (w.type == GuiWidget::Type::filter)
            mode = juce::jmax (0, juce::StringArray { "lowpass", "lowpass24", "highpass", "highpass24", "bandpass" }.indexOf (w.mode));

        float cutoffScale = 0.0f;

        if (w.type == GuiWidget::Type::filter)
        {
            const auto unit = unitsById.count (p1) > 0 ? unitsById.at (p1) : juce::String();
            cutoffScale = unit.equalsIgnoreCase ("Hz") ? 1.0f : (unit.equalsIgnoreCase ("kHz") ? 1000.0f : 0.0f);
        }

        gui.widgetRows << "        { Kind::" << kind << ", " << area.getX() << ", " << area.getY() << ", " << area.getWidth() << ", " << area.getHeight()
                       << ", " << strip << ", " << literalOrNull (p1) << ", " << literalOrNull (p2) << ", " << literalOrNull (p3) << ", "
                       << literalOrNull (p4) << ", " << literalOrNull (source) << ", 0x" << juce::String::toHexString ((juce::int64) colour) << "u, "
                       << vertical << ", " << count << ", " << juce::String (w.threshold, 4) << "f, " << mode << ", "
                       << (displayIds.contains (source) ? 1 : 0) << ", " << juce::String (cutoffScale, 1) << "f },\n";
        ++gui.numWidgets;
    }

    return gui;
}

//==============================================================================
juce::File PluginExporter::findCompiler()
{
    // Beside the program in a finished install; in the build folder while developing.
    for (const auto& candidate : { besideProgram ("llvm-mingw"), juce::File (STELLA_LLVM_MINGW_DIR) })
        if (compilerIn (candidate).existsAsFile())
            return candidate;

    return {};
}

juce::File PluginExporter::findClapHeaders()
{
    for (const auto& candidate : { besideProgram ("clap").getChildFile ("include"), juce::File (STELLA_CLAP_INCLUDE_DIR) })
        if (candidate.getChildFile ("clap").getChildFile ("clap.h").existsAsFile())
            return candidate;

    return {};
}

juce::File PluginExporter::findVst3Headers()
{
    for (const auto& candidate : { besideProgram ("vst3"), juce::File (STELLA_VST3_INCLUDE_DIR) })
        if (candidate.getChildFile ("pluginterfaces").getChildFile ("base").getChildFile ("funknown.h").existsAsFile())
            return candidate;

    return {};
}

juce::File PluginExporter::defaultExportFolder (const juce::String& pluginName)
{
    return juce::File::getSpecialLocation (juce::File::userDocumentsDirectory)
               .getChildFile ("Stella AI Studio")
               .getChildFile ("Exports")
               .getChildFile (juce::File::createLegalFileName (pluginName));
}

//==============================================================================
PluginExporter::Result PluginExporter::exportPlugins (const juce::File& projectFolder, const ProjectInfo& info, const juce::File& destinationFolder,
                                                      const Gui& gui)
{
    Result result;
    const auto started = juce::Time::getMillisecondCounterHiRes();

    const auto toolchain = findCompiler();
    const auto clapHeaders = findClapHeaders();
    const auto vst3Headers = findVst3Headers();

    if (toolchain == juce::File() || clapHeaders == juce::File() || vst3Headers == juce::File())
    {
        result.log = "The plugin compiler that comes with Stella AI Studio is missing. Reinstall the studio.";
        return result;
    }

    // The work folder is the studio's own, outside the project.
    const auto work = juce::File::getSpecialLocation (juce::File::tempDirectory)
                          .getChildFile ("Stella AI Studio")
                          .getChildFile ("export-" + juce::File::createLegalFileName (info.uuid));

    work.deleteRecursively();

    if (! work.createDirectory())
    {
        result.log = "Couldn't create the build folder " + work.getFullPathName();
        return result;
    }

    juce::String graphSource;

    if (const auto graph = WasmCompiler::generateGraphSource (projectFolder.getChildFile (WasmCompiler::graphFileName), graphSource); graph.failed())
    {
        result.log = graph.getErrorMessage();
        return result;
    }

    // The VST3 class id: the project's own id, fixed when the project was made.
    juce::String vst3Id;
    const auto uuidHex = info.uuid.removeCharacters ("-{}").paddedLeft ('0', 32).substring (0, 32);

    for (int i = 0; i < 16; ++i)
        vst3Id << (i > 0 ? ", " : "") << "0x" << uuidHex.substring (i * 2, i * 2 + 2);

    // What the plugin calls itself. A MIDI effect is built as an instrument until plugins
    // can send MIDI.
    juce::String pluginInfo;
    pluginInfo << "// Generated by Stella AI Studio for this export.\n#pragma once\n\nnamespace stella::info\n{\n"
               << "    constexpr const char* name = " << literal (info.name) << ";\n"
               << "    constexpr const char* vendor = " << literal (info.vendor) << ";\n"
               << "    constexpr const char* id = " << literal (info.pluginId) << ";\n"
               << "    constexpr const char* version = " << literal (info.version) << ";\n"
               << "    constexpr const char* description = \"Made with Stella AI Studio\";\n"
               << "    constexpr bool isInstrument = " << (info.kind == PluginKind::effect ? "false" : "true") << ";\n"
               << "    constexpr unsigned char vst3Id[16] { " << vst3Id << " };\n"
               << "}\n";

    auto writeData = [&work] (const char* name, const char* data, int size)
    {
        return work.getChildFile (name).replaceWithData (data, (size_t) size);
    };

    if (! WasmCompiler::writeRuntime (work)
        || ! writeData ("stella_clap.cpp", StellaRuntimeData::stella_clap_cpp, StellaRuntimeData::stella_clap_cppSize)
        || ! writeData ("stella_vst3.cpp", StellaRuntimeData::stella_vst3_cpp, StellaRuntimeData::stella_vst3_cppSize)
        || ! writeData ("stella_standalone.cpp", StellaRuntimeData::stella_standalone_cpp, StellaRuntimeData::stella_standalone_cppSize)
        || ! writeData ("stella_gui.h", StellaRuntimeData::stella_gui_h, StellaRuntimeData::stella_gui_hSize)
        || ! writeData ("stella_gui.cpp", StellaRuntimeData::stella_gui_cpp, StellaRuntimeData::stella_gui_cppSize)
        || ! writeData ("stella_keys.h", StellaRuntimeData::stella_keys_h, StellaRuntimeData::stella_keys_hSize)
        || ! writeData ("stella_gui_win32.cpp", StellaRuntimeData::stella_gui_win32_cpp, StellaRuntimeData::stella_gui_win32_cppSize)
        || ! writeData ("stb_image.h", StellaRuntimeData::stb_image_h, StellaRuntimeData::stb_image_hSize)
        || ! work.getChildFile ("stella_gui_data.cpp").replaceWithText (guiSource (gui))
        || ! work.getChildFile ("stella_graph.cpp").replaceWithText (graphSource)
        || ! work.getChildFile ("stella_plugin_info.h").replaceWithText (pluginInfo))
    {
        result.log = "Couldn't write into the build folder " + work.getFullPathName();
        return result;
    }

    const auto modules = projectFolder.getChildFile ("modules");
    auto moduleFiles = modules.findChildFiles (juce::File::findFiles, false, "*.cpp");
    moduleFiles.sort();

    const auto baseName = juce::File::createLegalFileName (info.name);
    const auto builtClap = work.getChildFile (baseName + ".clap");
    const auto builtVst3 = work.getChildFile (baseName + ".vst3");
    const auto builtApp = work.getChildFile (baseName + ".exe");

    // One compile per format, all at once: the same sources apart from the wrapper.
    enum class Target { clap, vst3, app };

    auto commandFor = [&] (Target target)
    {
        juce::StringArray args;
        args.add (compilerIn (toolchain).getFullPathName());
        args.addArray ({ "-O2", "-std=c++17", "-static", "-fvisibility=hidden", "-fno-exceptions", "-fno-rtti", "-DNDEBUG", "-Wall" });
        args.add (target == Target::app ? "-mwindows" : "-shared");   // an app with a window, or a plugin library
        args.add ("-I" + work.getFullPathName());
        args.add ("-I" + modules.getFullPathName());

        if (target != Target::app)
            args.add ("-I" + (target == Target::vst3 ? vst3Headers : clapHeaders).getFullPathName());

        args.add ("-o");
        args.add ((target == Target::vst3 ? builtVst3 : target == Target::clap ? builtClap : builtApp).getFullPathName());

        for (const auto* source : { "stella_runtime.cpp", "stella_graph.cpp", "stella_gui.cpp", "stella_gui_win32.cpp", "stella_gui_data.cpp" })
            args.add (work.getChildFile (source).getFullPathName());

        args.add (work.getChildFile (target == Target::vst3 ? "stella_vst3.cpp"
                                   : target == Target::clap ? "stella_clap.cpp" : "stella_standalone.cpp").getFullPathName());

        if (target == Target::vst3)
            args.add (vst3Headers.getChildFile ("pluginterfaces").getChildFile ("base").getChildFile ("funknown.cpp").getFullPathName());

        for (const auto& file : moduleFiles)
            args.add (file.getFullPathName());

        args.addArray ({ "-Wl,--strip-all", "-luser32", "-lgdi32" });

        if (target != Target::clap)
            args.add ("-lole32");

        if (target == Target::app)
            args.add ("-lwinmm");   // MIDI inputs

        return args;
    };

    juce::ChildProcess clapCompiler, vst3Compiler, appCompiler;

    if (! clapCompiler.start (commandFor (Target::clap), juce::ChildProcess::wantStdOut | juce::ChildProcess::wantStdErr)
        || ! vst3Compiler.start (commandFor (Target::vst3), juce::ChildProcess::wantStdOut | juce::ChildProcess::wantStdErr)
        || ! appCompiler.start (commandFor (Target::app), juce::ChildProcess::wantStdOut | juce::ChildProcess::wantStdErr))
    {
        result.log = "The plugin compiler couldn't be started.";
        return result;
    }

    auto tidy = [&] (juce::String log)
    {
        return log.replace (modules.getFullPathName() + juce::File::getSeparatorString(), "modules/")
                  .replace (work.getFullPathName() + juce::File::getSeparatorString(), "")
                  .trim();
    };

    const auto clapLog = tidy (clapCompiler.readAllProcessOutput());
    const auto vst3Log = tidy (vst3Compiler.readAllProcessOutput());
    const auto appLog = tidy (appCompiler.readAllProcessOutput());
    clapCompiler.waitForProcessToFinish (5000);
    vst3Compiler.waitForProcessToFinish (5000);
    appCompiler.waitForProcessToFinish (5000);

    const bool clapOk = clapCompiler.getExitCode() == 0 && builtClap.existsAsFile();
    const bool vst3Ok = vst3Compiler.getExitCode() == 0 && builtVst3.existsAsFile();
    const bool appOk = appCompiler.getExitCode() == 0 && builtApp.existsAsFile();

    result.log = clapLog;

    if (! vst3Ok && vst3Log.isNotEmpty() && vst3Log != clapLog)
        result.log << (result.log.isNotEmpty() ? "\n\n" : "") << "VST3:\n" << vst3Log;

    if (! appOk && appLog.isNotEmpty() && appLog != clapLog)
        result.log << (result.log.isNotEmpty() ? "\n\n" : "") << "Standalone app:\n" << appLog;

    result.seconds = (juce::Time::getMillisecondCounterHiRes() - started) / 1000.0;

    if (! clapOk || ! vst3Ok || ! appOk)
    {
        if (result.log.isEmpty())
            result.log = "The plugin compiler stopped without saying why.";

        return result;
    }

    // Into the exports folder: <name>.clap, the VST3 bundle <name>.vst3\Contents\x86_64-win\<name>.vst3,
    // and <name>.exe. A DAW holding an old file locked (or the app running) makes this fail: say so.
    destinationFolder.createDirectory();
    const auto clapTarget = destinationFolder.getChildFile (baseName + ".clap");
    const auto appTarget = destinationFolder.getChildFile (baseName + ".exe");
    const auto bundle = destinationFolder.getChildFile (baseName + ".vst3");

    if (bundle.existsAsFile())
        bundle.deleteFile();   // an old single-file VST3 in the way

    const auto vst3Target = bundle.getChildFile ("Contents").getChildFile ("x86_64-win").getChildFile (baseName + ".vst3");
    vst3Target.getParentDirectory().createDirectory();

    if (! builtClap.copyFileTo (clapTarget) || ! builtVst3.copyFileTo (vst3Target))
    {
        result.log = (result.log.isNotEmpty() ? result.log + "\n\n" : juce::String())
                   + "Couldn't write into " + destinationFolder.getFullPathName() + ". If a DAW has the plugin loaded, close it and export again.";
        return result;
    }

    if (! builtApp.copyFileTo (appTarget))
    {
        result.log = (result.log.isNotEmpty() ? result.log + "\n\n" : juce::String())
                   + "Couldn't write " + appTarget.getFileName() + " into " + destinationFolder.getFullPathName()
                   + ". If the app is open, close it and export again.";
        return result;
    }

    result.ok = true;
    result.plugin = clapTarget;
    result.vst3 = bundle;
    result.app = appTarget;
    return result;
}
