// C:\workspace\Stella AI Studio\src\stella_gui.h
//
// The exported plugin's GUI, without JUCE. The studio bakes the GUI at export: one
// background image with everything that never moves, and strips of frames for each
// control's moving part (stella_gui_data.cpp, generated). The plugin draws a frame from
// those, plus what it draws live: meter bars, scope traces, envelope and filter curves
// and XY dots, into a plain 32-bit pixel buffer that the window shows.

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace stella::gui
{
    //==========================================================================
    // The baked GUI (stella_gui_data.cpp, generated by the studio).
    enum class Kind : int { knob, slider, toggle, selector, xy, meter, lamp, scope, envelope, filter, preset };

    struct Widget
    {
        Kind kind;
        int x, y, w, h;          // the moving part's area, in plugin pixels
        int strip;               // frames for knob, slider, switch, selector, lamp; else -1
        const char* param;       // the parameter (xy: x; envelope: attack; filter: cutoff)
        const char* param2;      // xy: y; envelope: decay; filter: resonance
        const char* param3;      // envelope: sustain
        const char* param4;      // envelope: release
        const char* source;      // meters, lamps, scopes: a signal or a module display
        std::uint32_t colour;    // the accent, 0xAARRGGBB
        int vertical;            // sliders, meters
        int count;               // selectors: positions
        float threshold;         // lamps
        int mode;                // meters: 0 peak, 1 RMS; filters: 0 LP, 1 LP24, 2 HP, 3 HP24, 4 BP
        int isDisplay;           // meters and lamps: the source is a module display (0..1)
        float cutoffScale;       // filters: 1 if the cutoff is in Hz, 1000 in kHz, 0 to map 20 Hz..20 kHz
    };

    struct Strip
    {
        const unsigned char* png;
        int size;
        int frameWidth, frameHeight, frames;
    };

    extern const int width, height;
    extern const unsigned char backgroundPng[];
    extern const int backgroundPngSize;
    extern const Strip strips[];
    extern const int numStrips;
    extern const Widget widgets[];
    extern const int numWidgets;

    /** The plugin's presets: values by parameter id. A preset widget steps through them. */
    struct PresetValue
    {
        const char* param;
        float value;
    };

    struct Preset
    {
        const PresetValue* values;
        int numValues;
    };

    extern const Preset presets[];
    extern const int numPresets;

    //==========================================================================
    /** What the GUI needs from the plugin. */
    class Host
    {
    public:
        virtual ~Host() = default;

        virtual int findParam (const char* id) = 0;                      // -1 if none
        virtual float getValue (int param) = 0;
        virtual void getRange (int param, float& min, float& max, float& def, float& skew) = 0;
        virtual void beginEdit (int param) = 0;
        virtual void setValue (int param, float value) = 0;
        virtual void endEdit (int param) = 0;

        /** Meters and lamps: the source's highest level since the last call (or its RMS),
            or a display's value. Scopes: the newest samples. */
        virtual float takeLevel (int widget, bool rms) = 0;
        virtual void readScope (int widget, float* destination, int numSamples) = 0;
    };

    //==========================================================================
    /** The window the host embeds the GUI in. Only on Windows so far: elsewhere create()
        gives nullptr and hosts show their own controls. */
    class Window
    {
    public:
        static std::unique_ptr<Window> create (Host& host);
        virtual ~Window() = default;

        /** parent: the host's window (an HWND on Windows). */
        virtual bool attach (void* parent) = 0;
        virtual void setVisible (bool visible) = 0;
    };

    //==========================================================================
    /** The GUI, drawn into a pixel buffer and driven by the mouse. Platform-free: the
        window around it (stella_gui_win32.cpp) shows the pixels and passes the mouse on. */
    class Editor
    {
    public:
        explicit Editor (Host& host);
        ~Editor();

        int getWidth() const noexcept    { return width; }
        int getHeight() const noexcept   { return height; }

        /** Draws a frame: 32-bit pixels, 0xAARRGGBB in memory order BGRA, top row first. */
        void render (std::uint32_t* pixels);

        void mouseDown (int x, int y, bool fine, bool doubleClick);
        void mouseDrag (int x, int y, bool fine);
        void mouseUp();
        void mouseWheel (int x, int y, float notches);

    private:
        struct Image
        {
            int width = 0, height = 0;
            std::vector<std::uint32_t> pixels;   // premultiplied
        };

        struct Bound
        {
            int param = -1, param2 = -1, param3 = -1, param4 = -1;
        };

        static Image decode (const unsigned char* png, int size);
        float proportionOf (int param) const;
        float valueAt (int param, float proportion) const;
        int widgetAt (int x, int y) const;
        void setFromPointer (int widget, int x, int y);

        void blitFrame (std::uint32_t* pixels, const Image& image, int frameHeight, int frame, int x, int y) const;
        void drawMeter (std::uint32_t* pixels, const Widget& w, int index);
        void drawScope (std::uint32_t* pixels, const Widget& w, int index);
        void drawCurve (std::uint32_t* pixels, const Widget& w, const Bound& bound);
        void drawXy (std::uint32_t* pixels, const Widget& w, const Bound& bound);

        Host& host;
        Image background;
        std::vector<Image> frames;
        std::vector<Bound> bound;
        std::vector<float> meterLevels;
        std::vector<float> scopeBuffer;

        void applyPreset (int index);

        int active = -1;
        int currentPreset = 0;
        int dragX = 0, dragY = 0;
        float startProportion = 0.0f;
    };
}
