// C:\workspace\Stella AI Studio\src\stella_gui.h
//
// The exported plugin's GUI, without JUCE. The studio bakes the GUI at export: one
// background image with everything that never moves, and strips of frames for each
// control's moving part (stella_gui_data.cpp, generated). The plugin draws a frame from
// those, plus what it draws live: meter bars, scope traces, envelope and filter curves,
// XY dots, a keyboard's keys that are down, and programmed elements (stella_elements.h,
// when the plugin has any: STELLA_ELEMENTS), into a plain 32-bit pixel buffer that the
// window shows.

#pragma once

#include <atomic>
#include <cstdint>
#include <memory>
#include <vector>

namespace stella::gui
{
    //==========================================================================
    // The baked GUI (stella_gui_data.cpp, generated by the studio).
    enum class Kind : int { knob, slider, toggle, selector, xy, meter, lamp, scope, envelope, filter, preset, keyboard, picture, custom };

    struct Widget
    {
        Kind kind;
        int x, y, w, h;          // the moving part's area, in plugin pixels
        int strip;               // frames for knob, slider, switch, selector, lamp, preset; a picture's
                                 // one frame (a picture, text or frame in front of something that
                                 // moves); else -1
        const char* param;       // the parameter (xy: x; envelope: attack; filter: cutoff)
        const char* param2;      // xy: y; envelope: decay; filter: resonance
        const char* param3;      // envelope: sustain
        const char* param4;      // envelope: release
        const char* source;      // meters, lamps, scopes: a signal or a module display
        std::uint32_t colour;    // the accent, 0xAARRGGBB
        int vertical;            // sliders, meters
        int count;               // selectors: positions; keyboards: the highest key (a MIDI note);
                                 // custom: its place in customElements
        float threshold;         // lamps
        int mode;                // meters: 0 peak, 1 RMS; filters: 0 LP, 1 LP24, 2 HP, 3 HP24, 4 BP;
                                 // keyboards: the lowest key
        int isDisplay;           // meters and lamps: the source is a module display (0..1)
        float cutoffScale;       // filters: 1 if the cutoff is in Hz, 1000 in kHz, 0 to map 20 Hz..20 kHz
    };

    struct Strip
    {
        const unsigned char* png;
        int size;
        int frameWidth, frameHeight, frames;
    };

    extern const int width, height;
    extern const unsigned char backgroundPng[];
    extern const int backgroundPngSize;
    extern const Strip strips[];
    extern const int numStrips;
    extern const Widget widgets[];
    extern const int numWidgets;

    /** The plugin's presets: values by parameter id. A preset widget steps through them. */
    struct PresetValue
    {
        const char* param;
        float value;
    };

    struct Preset
    {
        const PresetValue* values;
        int numValues;
    };

    extern const Preset presets[];
    extern const int numPresets;

    /** A programmed element: what its widget (Kind::custom) tells it from the layout. Its
        parameters by slot: 0 the widget's param, then its roles. */
    struct CustomElement
    {
        const char* type;                    // the element's name (STELLA_ELEMENT)
        const char* label;
        const char* const* options;
        int numOptions;
        const char* const* roles;            // role names, slots 1 and up
        const char* const* roleParams;       // their parameter ids
        int numRoles;
        const char* const* slotNames;        // each slot's parameter's name and unit, slot 0 first
        const char* const* slotUnits;
        const char* const* settingKeys;      // "settings", as text
        const char* const* settingValues;
        int numSettings;
    };

    extern const CustomElement customElements[];
    extern const int numCustomElements;

    //==========================================================================
    /** What the GUI needs from the plugin. */
    class Host
    {
    public:
        virtual ~Host() = default;

        virtual int findParam (const char* id) = 0;                      // -1 if none
        virtual float getValue (int param) = 0;
        virtual void getRange (int param, float& min, float& max, float& def, float& skew) = 0;
        virtual void beginEdit (int param) = 0;
        virtual void setValue (int param, float value) = 0;
        virtual void endEdit (int param) = 0;

        /** Meters and lamps: the source's highest level since the last call (or its RMS),
            or a display's value. Scopes: the newest samples. */
        virtual float takeLevel (int widget, bool rms) = 0;
        virtual void readScope (int widget, float* destination, int numSamples) = 0;

        /** The keyboard: a note starts (velocity 0..1) or stops (velocity 0). The plugin
            plays it as if it came from the host. */
        virtual void playNote (int note, float velocity) = 0;

        /** Whether a note is sounding, from the keyboard, the host or a MIDI keyboard: the
            keyboard shows it down. */
        virtual bool isNoteDown (int note) = 0;
    };

    //==========================================================================
    /** The keyboard's notes on their way to the audio (one writer, the GUI; one reader,
        the audio), and which notes are sounding, for the keyboards to show. */
    class Notes
    {
    public:
        /** GUI thread: a note starts (velocity 1..127) or stops (0). Dropped when the audio
            isn't running to take them. */
        void push (int note, int velocity) noexcept
        {
            if (note < 0 || note > 127)
                return;

            const auto h = head.load (std::memory_order_relaxed);
            const auto next = (h + 1) % size;

            if (next == tail.load (std::memory_order_acquire))
                return;

            ring[h] = { (std::uint8_t) note, (std::uint8_t) (velocity < 0 ? 0 : (velocity > 127 ? 127 : velocity)) };
            head.store (next, std::memory_order_release);
        }

        /** Audio thread: the next note from the GUI, if there is one. */
        bool pop (int& note, int& velocity) noexcept
        {
            const auto t = tail.load (std::memory_order_relaxed);

            if (t == head.load (std::memory_order_acquire))
                return false;

            note = ring[t].note;
            velocity = ring[t].velocity;
            tail.store ((t + 1) % size, std::memory_order_release);
            return true;
        }

        /** Audio thread: a note started or stopped, wherever it came from. */
        void sounding (int note, bool on) noexcept
        {
            if (note >= 0 && note < 128)
                down[note].store (on ? 1 : 0, std::memory_order_relaxed);
        }

        void clear() noexcept
        {
            for (auto& d : down)
                d.store (0, std::memory_order_relaxed);
        }

        bool isDown (int note) const noexcept
        {
            return note >= 0 && note < 128 && down[note].load (std::memory_order_relaxed) != 0;
        }

    private:
        static constexpr std::uint32_t size = 256;

        struct Note
        {
            std::uint8_t note, velocity;
        };

        Note ring[size] {};
        std::atomic<std::uint32_t> head { 0 }, tail { 0 };
        std::atomic<std::uint8_t> down[128] {};
    };

    //==========================================================================
    /** The window the host embeds the GUI in. Only on Windows so far: elsewhere create()
        gives nullptr and hosts show their own controls. */
    class Window
    {
    public:
        static std::unique_ptr<Window> create (Host& host);
        virtual ~Window() = default;

        /** parent: the host's window (an HWND on Windows). */
        virtual bool attach (void* parent) = 0;
        virtual void setVisible (bool visible) = 0;
    };

    //==========================================================================
    /** The GUI, drawn into a pixel buffer and driven by the mouse. Platform-free: the
        window around it (stella_gui_win32.cpp) shows the pixels and passes the mouse on. */
    class Editor
    {
    public:
        explicit Editor (Host& host);
        ~Editor();   // a key still held stops

        int getWidth() const noexcept    { return width; }
        int getHeight() const noexcept   { return height; }

        /** Draws a frame: 32-bit pixels, 0xAARRGGBB in memory order BGRA, top row first. */
        void render (std::uint32_t* pixels);

        void mouseDown (int x, int y, bool fine, bool doubleClick);
        void mouseDrag (int x, int y, bool fine);
        void mouseUp();
        void mouseWheel (int x, int y, float notches);
        void mouseMove (int x, int y);   // no button down: programmed elements hear it
        void mouseExit();

    private:
        struct Image
        {
            int width = 0, height = 0;
            std::vector<std::uint32_t> pixels;   // premultiplied
        };

        struct Bound
        {
            int param = -1, param2 = -1, param3 = -1, param4 = -1;
        };

        static Image decode (const unsigned char* png, int size);
        float proportionOf (int param) const;
        float valueAt (int param, float proportion) const;
        int widgetAt (int x, int y) const;
        void setFromPointer (int widget, int x, int y);

        void blitFrame (std::uint32_t* pixels, const Image& image, int frameHeight, int frame, int x, int y) const;
        void drawMeter (std::uint32_t* pixels, const Widget& w, int index);
        void drawScope (std::uint32_t* pixels, const Widget& w, int index);
        void drawCurve (std::uint32_t* pixels, const Widget& w, const Bound& bound);
        void drawXy (std::uint32_t* pixels, const Widget& w, const Bound& bound);
        void drawKeyboard (std::uint32_t* pixels, const Widget& w, int index);

        /** The key under the pointer plays (the one before stops); off the keys, none. */
        void playKey (int widget, int x, int y);
        void releaseKey();

        /** The programmed elements (stella_gui.cpp), when the plugin has any. */
        struct Elements;
        std::unique_ptr<Elements> elements;
        void drawElement (std::uint32_t* pixels, int index);
        void drawPopups (std::uint32_t* pixels);
        void blitPixels (std::uint32_t* pixels, const std::uint32_t* source, int x, int y, int w, int h) const;

        Host& host;
        Image background;
        std::vector<Image> frames;
        std::vector<Bound> bound;
        std::vector<float> meterLevels;
        std::vector<float> scopeBuffer;

        void applyPreset (int index);

        int active = -1;
        int heldNote = -1, heldKeyboard = -1;   // the key the mouse holds down, and on which keyboard
        int currentPreset = 0;
        int dragX = 0, dragY = 0;
        float startProportion = 0.0f;
    };
}
