# C:\workspace\Stella AI Studio\src\StellaToolchain.cmake
#
# The tools behind the live preview and Export, downloaded once into build/_deps:
#   Wasmtime 39.0.1 (C API): runs the plugin being built, live, in a sandbox;
#   wasi-sdk 25: the compiler that turns a plugin's C++ into WebAssembly;
#   llvm-mingw 20260922: the compiler that builds the exported plugin for Windows;
#   CLAP 1.2.10 and VST3 3.8.1 (pluginterfaces, MIT licensed): the plugin formats' headers.
# The compilers and headers ship with the studio, so users don't need anything installed.
#
# Sets STELLA_WASMTIME_DIR, STELLA_WASI_SDK_DIR, STELLA_LLVM_MINGW_DIR, STELLA_CLAP_DIR and
# STELLA_VST3_DIR, and writes StellaToolchainPaths.h into the build folder.

set(STELLA_DEPS_DIR "${CMAKE_BINARY_DIR}/_deps")
file(MAKE_DIRECTORY "${STELLA_DEPS_DIR}")

function(stella_fetch name url sha256 folder result_var)
    set(dir "${STELLA_DEPS_DIR}/${folder}")
    set(stamp "${STELLA_DEPS_DIR}/${name}.done")

    if(NOT EXISTS "${stamp}" OR NOT IS_DIRECTORY "${dir}")
        get_filename_component(archive_name "${url}" NAME)
        set(archive "${STELLA_DEPS_DIR}/${archive_name}")

        message(STATUS "Stella: downloading ${archive_name} (once)")
        file(DOWNLOAD "${url}" "${archive}" STATUS status TLS_VERIFY ON EXPECTED_HASH SHA256=${sha256})
        list(GET status 0 code)

        if(NOT code EQUAL 0)
            message(FATAL_ERROR "Stella: couldn't download ${url}: ${status}")
        endif()

        message(STATUS "Stella: unpacking ${archive_name}")
        file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${STELLA_DEPS_DIR}")
        file(REMOVE "${archive}")

        if(NOT IS_DIRECTORY "${dir}")
            message(FATAL_ERROR "Stella: ${archive_name} didn't unpack to ${dir}")
        endif()

        file(WRITE "${stamp}" "${url}\n")
    endif()

    set(${result_var} "${dir}" PARENT_SCOPE)
endfunction()

set(_stella_wasmtime "https://github.com/bytecodealliance/wasmtime/releases/download/v39.0.1")
set(_stella_wasisdk  "https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25")
set(_stella_mingw    "https://github.com/mstorsjo/llvm-mingw/releases/download/20260922")

if(WIN32)
    stella_fetch(wasmtime "${_stella_wasmtime}/wasmtime-v39.0.1-x86_64-windows-c-api.zip"
        "4939453176b7a86cf4f2cd9839da100a4e30f0505a4a471f2dba92a012e4975c"
        "wasmtime-v39.0.1-x86_64-windows-c-api" STELLA_WASMTIME_DIR)

    stella_fetch(wasi-sdk "${_stella_wasisdk}/wasi-sdk-25.0-x86_64-windows.tar.gz"
        "ebd4868f95a6e764bf29283e3bdf54df0df3902a29737176da9c17da218b939b"
        "wasi-sdk-25.0-x86_64-windows" STELLA_WASI_SDK_DIR)

    stella_fetch(llvm-mingw "${_stella_mingw}/llvm-mingw-20260922-ucrt-x86_64.zip"
        "e3ad77d117a4bea19a7a3b333341824d79a5a371004a10e25b8504e7b3047666"
        "llvm-mingw-20260922-ucrt-x86_64" STELLA_LLVM_MINGW_DIR)
elseif(UNIX AND NOT APPLE AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    stella_fetch(wasmtime "${_stella_wasmtime}/wasmtime-v39.0.1-x86_64-linux-c-api.tar.xz"
        "f1e2b41f9c1d8d097506ad584e7d56140ebfdc6b6e5ae7cbfc8c829dfff3487e"
        "wasmtime-v39.0.1-x86_64-linux-c-api" STELLA_WASMTIME_DIR)

    stella_fetch(wasi-sdk "${_stella_wasisdk}/wasi-sdk-25.0-x86_64-linux.tar.gz"
        "52640dde13599bf127a95499e61d6d640256119456d1af8897ab6725bcf3d89c"
        "wasi-sdk-25.0-x86_64-linux" STELLA_WASI_SDK_DIR)

    stella_fetch(llvm-mingw "${_stella_mingw}/llvm-mingw-20260922-ucrt-ubuntu-22.04-x86_64.tar.xz"
        "bb7bb7654b33d5aa8712acb837c963b2e0c56352560c76105270a3268c665c21"
        "llvm-mingw-20260922-ucrt-ubuntu-22.04-x86_64" STELLA_LLVM_MINGW_DIR)
else()
    message(FATAL_ERROR "Stella: the live preview's tools are set up for Windows so far; macOS comes later.")
endif()

stella_fetch(clap "https://codeload.github.com/free-audio/clap/tar.gz/refs/tags/1.2.10"
    "58fdb977c6678859c15d57942378b651399178f49a3a8ecad1813b9f231dc096"
    "clap-1.2.10" STELLA_CLAP_DIR)

stella_fetch(vst3-pluginterfaces "https://codeload.github.com/steinbergmedia/vst3_pluginterfaces/tar.gz/refs/tags/v3.8.1_build_84"
    "19e88e225b6ecb4a3c429d3ff2fd511be9c6c8b8b1c7e86b05949b45c0553e2d"
    "vst3_pluginterfaces-3.8.1_build_84" _stella_vst3_interfaces)

# The headers are included as "pluginterfaces/...", so they need a folder of that name.
set(STELLA_VST3_DIR "${STELLA_DEPS_DIR}/vst3")

if(NOT EXISTS "${STELLA_VST3_DIR}/pluginterfaces/base/funknown.h")
    file(COPY "${_stella_vst3_interfaces}/" DESTINATION "${STELLA_VST3_DIR}/pluginterfaces")
endif()

# Where the compiler lives while developing, for WasmCompiler.cpp. Only rewritten when it
# changes, so it doesn't trigger rebuilds.
set(STELLA_GENERATED_DIR "${CMAKE_BINARY_DIR}/stella_generated")
file(WRITE "${STELLA_GENERATED_DIR}/StellaToolchainPaths.h.new"
     "// Generated by CMake: where the bundled compilers and headers are while developing.\n#pragma once\n#define STELLA_WASI_SDK_DIR \"${STELLA_WASI_SDK_DIR}\"\n#define STELLA_LLVM_MINGW_DIR \"${STELLA_LLVM_MINGW_DIR}\"\n#define STELLA_CLAP_INCLUDE_DIR \"${STELLA_CLAP_DIR}/include\"\n#define STELLA_VST3_INCLUDE_DIR \"${STELLA_VST3_DIR}\"\n")
configure_file("${STELLA_GENERATED_DIR}/StellaToolchainPaths.h.new" "${STELLA_GENERATED_DIR}/StellaToolchainPaths.h" COPYONLY)
