// C:\workspace\Stella AI Studio\src\WasmCompiler.cpp

#include "WasmCompiler.h"

#include "StellaRuntimeData.h"
#include "StellaToolchainPaths.h"

namespace
{
    juce::File clangIn (const juce::File& sdk)
    {
       #if JUCE_WINDOWS
        return sdk.getChildFile ("bin").getChildFile ("clang++.exe");
       #else
        return sdk.getChildFile ("bin").getChildFile ("clang++");
       #endif
    }

    /** A C++ string literal for any text. */
    juce::String literal (const juce::String& text)
    {
        juce::String result ("\"");

        for (auto c : text)
        {
            if (c == '"' || c == '\\')
                result << '\\' << juce::String::charToString (c);
            else if (c >= 32 && c < 127)
                result << juce::String::charToString (c);
        }

        return result + "\"";
    }

    bool isIdentifier (const juce::String& text)
    {
        return text.isNotEmpty()
            && text.containsOnly ("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")
            && ! juce::CharacterFunctions::isDigit (text[0]);
    }

    /** "voices.out" -> ("voices", "out"). Port names may have spaces ("out L"). */
    bool splitEnd (const juce::String& end, juce::String& module, juce::String& port)
    {
        const auto dot = end.indexOfChar ('.');

        if (dot <= 0 || dot >= end.length() - 1)
            return false;

        module = end.substring (0, dot).trim();
        port = end.substring (dot + 1).trim();
        return module.isNotEmpty() && port.isNotEmpty();
    }

    bool writeResource (const juce::File& file, const char* data, int size)
    {
        return file.replaceWithData (data, (size_t) size);
    }

    /** Bytes as the body of a C++ array, 24 to a line. */
    void appendBytes (juce::MemoryOutputStream& out, const char* data, int size)
    {
        static const char* const hex = "0123456789abcdef";
        const auto* bytes = reinterpret_cast<const unsigned char*> (data);
        char line[24 * 5 + 2];

        for (int i = 0; i < size; i += 24)
        {
            auto* c = line;

            for (int j = i; j < juce::jmin (size, i + 24); ++j)
            {
                *c++ = '0'; *c++ = 'x';
                *c++ = hex[bytes[j] >> 4];
                *c++ = hex[bytes[j] & 15];
                *c++ = ',';
            }

            *c++ = '\n';
            out.write (line, (size_t) (c - line));
        }
    }

    juce::String fontsHeader()
    {
        juce::MemoryOutputStream out;
        out << "// Generated by Stella AI Studio: the Inter font (SIL Open Font License 1.1, rsms.me/inter), regular and bold.\n"
            << "#pragma once\n\nnamespace stella::ui::fonts\n{\n    static const unsigned char regular[] =\n    {\n";
        appendBytes (out, StellaRuntimeData::inter_regular_ttf, StellaRuntimeData::inter_regular_ttfSize);
        out << "    };\n\n    static const unsigned char bold[] =\n    {\n";
        appendBytes (out, StellaRuntimeData::inter_bold_ttf, StellaRuntimeData::inter_bold_ttfSize);
        out << "    };\n}\n";
        return out.toString();
    }

    struct Resource
    {
        const char* name;
        const char* data;
        int size;
    };

    std::vector<Resource> elementRuntimeFiles()
    {
        return { { "stella_element_api.h", StellaRuntimeData::stella_element_api_h, StellaRuntimeData::stella_element_api_hSize },
                 { "stella_element_host.h", StellaRuntimeData::stella_element_host_h, StellaRuntimeData::stella_element_host_hSize },
                 { "stella_elements.h", StellaRuntimeData::stella_elements_h, StellaRuntimeData::stella_elements_hSize },
                 { "stella_elements.cpp", StellaRuntimeData::stella_elements_cpp, StellaRuntimeData::stella_elements_cppSize },
                 { "stb_truetype.h", StellaRuntimeData::stb_truetype_h, StellaRuntimeData::stb_truetype_hSize } };
    }

    /** Which version of the elements' runtime this studio carries: its compiled form is kept by it. */
    juce::String elementRuntimeKey()
    {
        std::uint64_t hash = 14695981039346656037ull;

        auto add = [&hash] (const char* data, int size)
        {
            for (int i = 0; i < size; ++i)
                hash = (hash ^ (std::uint8_t) data[i]) * 1099511628211ull;
        };

        for (const auto& file : elementRuntimeFiles())
            add (file.data, file.size);

        add (StellaRuntimeData::inter_regular_ttf, StellaRuntimeData::inter_regular_ttfSize);
        add (StellaRuntimeData::inter_bold_ttf, StellaRuntimeData::inter_bold_ttfSize);
        return juce::String::toHexString ((juce::int64) hash);
    }

    bool isQuote (juce::juce_wchar c)    { return c == '"'; }

    /** The STELLA_ELEMENT (Name, "description") lines of a file. */
    void scanElements (const juce::String& text, const juce::String& file, juce::Array<WasmCompiler::ElementSource>& found)
    {
        const juce::String macro ("STELLA_ELEMENT");

        for (int at = text.indexOf (macro); at >= 0; at = text.indexOf (at + macro.length(), macro))
        {
            auto p = text.getCharPointer() + at + macro.length();
            auto skipSpace = [&p] { while (! p.isEmpty() && p.isWhitespace()) ++p; };

            skipSpace();

            if (*p != '(')
                continue;

            ++p;
            skipSpace();
            juce::String name;

            while (! p.isEmpty() && (p.isLetterOrDigit() || *p == '_'))
                name += juce::String::charToString (*p++);

            skipSpace();

            if (name.isEmpty() || *p != ',')
                continue;

            ++p;
            juce::String description;

            // One or more string literals in a row.
            for (;;)
            {
                skipSpace();

                if (! isQuote (*p))
                    break;

                ++p;

                while (! p.isEmpty() && ! isQuote (*p))
                {
                    if (*p == '\\' && ! (p + 1).isEmpty())
                        ++p;

                    description += juce::String::charToString (*p++);
                }

                if (! p.isEmpty())
                    ++p;
            }

            found.add ({ name, description, file });
        }
    }
}

//==============================================================================
juce::File WasmCompiler::findCompiler()
{
    // Beside the program in a finished install; in the build folder while developing.
    const auto besideProgram = juce::File::getSpecialLocation (juce::File::currentExecutableFile)
                                   .getParentDirectory().getChildFile ("wasi-sdk");

    for (const auto& candidate : { besideProgram, juce::File (STELLA_WASI_SDK_DIR) })
        if (clangIn (candidate).existsAsFile())
            return candidate;

    return {};
}

//==============================================================================
juce::Result WasmCompiler::generateGraphSource (const juce::File& graphFile, juce::String& source)
{
    juce::var graph;
    const auto parsed = juce::JSON::parse (graphFile.loadFileAsString(), graph);

    if (parsed.failed() || ! graph.isObject())
        return juce::Result::fail ("graph.json isn't valid JSON: " + parsed.getErrorMessage());

    const auto* modules = graph.getProperty ("modules", {}).getArray();
    const auto* wires = graph.getProperty ("wires", {}).getArray();

    if (modules == nullptr || modules->isEmpty())
        return juce::Result::fail ("graph.json has no modules.");

    juce::String moduleRows, wireRows;

    for (const auto& module : *modules)
    {
        const auto id = module.getProperty ("id", {}).toString().trim();
        const auto type = module.getProperty ("type", {}).toString().trim();

        if (! isIdentifier (id) || id == "plugin")
            return juce::Result::fail ("graph.json: \"" + id + "\" can't be a module id (letters, digits and _ only, and not \"plugin\").");

        if (! isIdentifier (type))
            return juce::Result::fail ("graph.json: \"" + type + "\" isn't a module type name.");

        moduleRows << "        { " << literal (id) << ", " << literal (type) << " },\n";
    }

    int numWires = 0;

    if (wires != nullptr)
    {
        for (const auto& wire : *wires)
        {
            juce::String fromModule, fromPort, toModule, toPort;

            if (! splitEnd (wire.getProperty ("from", {}).toString(), fromModule, fromPort)
                || ! splitEnd (wire.getProperty ("to", {}).toString(), toModule, toPort))
                return juce::Result::fail ("graph.json: a wire needs \"from\" and \"to\" like \"filter.out\".");

            wireRows << "        { " << literal (fromModule) << ", " << literal (fromPort) << ", "
                     << literal (toModule) << ", " << literal (toPort) << " },\n";
            ++numWires;
        }
    }

    if (numWires == 0)
        wireRows = "        { \"\", \"\", \"\", \"\" },\n";   // an array can't be empty; the count says 0

    source.clear();
    source << "// Generated by Stella AI Studio from graph.json. Don't edit: it's rewritten on every build.\n\n"
           << "#include \"stella_runtime.h\"\n\n"
           << "namespace stella\n{\n"
           << "    extern const GraphModule graphModules[]\n    {\n" << moduleRows << "    };\n\n"
           << "    extern const int numGraphModules = " << modules->size() << ";\n\n"
           << "    extern const GraphWire graphWires[]\n    {\n" << wireRows << "    };\n\n"
           << "    extern const int numGraphWires = " << numWires << ";\n"
           << "}\n";

    return juce::Result::ok();
}

bool WasmCompiler::writeRuntime (const juce::File& folder)
{
    return writeResource (folder.getChildFile ("stella_api.h"), StellaRuntimeData::stella_api_h, StellaRuntimeData::stella_api_hSize)
        && writeResource (folder.getChildFile ("stella_runtime.h"), StellaRuntimeData::stella_runtime_h, StellaRuntimeData::stella_runtime_hSize)
        && writeResource (folder.getChildFile ("stella_runtime.cpp"), StellaRuntimeData::stella_runtime_cpp, StellaRuntimeData::stella_runtime_cppSize);
}

//==============================================================================
juce::Array<WasmCompiler::ElementSource> WasmCompiler::findElements (const juce::File& projectFolder)
{
    juce::Array<ElementSource> found;
    auto files = projectFolder.getChildFile (elementsFolderName).findChildFiles (juce::File::findFiles, false, "*.cpp");
    files.sort();

    for (const auto& file : files)
        scanElements (file.loadFileAsString(), juce::String (elementsFolderName) + "/" + file.getFileName(), found);

    return found;
}

bool WasmCompiler::writeElementRuntime (const juce::File& folder)
{
    for (const auto& file : elementRuntimeFiles())
        if (! writeResource (folder.getChildFile (file.name), file.data, file.size))
            return false;

    const auto fonts = folder.getChildFile ("stella_fonts.h");
    const auto text = fontsHeader();
    return (fonts.existsAsFile() && fonts.loadFileAsString() == text) || fonts.replaceWithText (text);
}

WasmCompiler::Result WasmCompiler::compileElements (const juce::File& projectFolder, const juce::String& projectId)
{
    Result result;
    const auto started = juce::Time::getMillisecondCounterHiRes();
    const auto elements = projectFolder.getChildFile (elementsFolderName);

    auto files = elements.findChildFiles (juce::File::findFiles, false, "*.cpp");
    files.sort();

    if (files.isEmpty())
    {
        result.ok = true;   // nothing to build: the GUI has no programmed elements
        return result;
    }

    const auto sdk = findCompiler();

    if (sdk == juce::File())
    {
        result.log = "The plugin compiler that comes with Stella AI Studio is missing. Reinstall the studio.";
        return result;
    }

    const auto studioTemp = juce::File::getSpecialLocation (juce::File::tempDirectory).getChildFile ("Stella AI Studio");
    const auto work = studioTemp.getChildFile ("build-" + juce::File::createLegalFileName (projectId));
    const auto runtime = studioTemp.getChildFile ("element-runtime");

    if ((! work.isDirectory() && ! work.createDirectory()) || (! runtime.isDirectory() && ! runtime.createDirectory()))
    {
        result.log = "Couldn't create the build folder " + work.getFullPathName();
        return result;
    }

    auto baseArgs = [&sdk]
    {
        juce::StringArray args;
        args.add (clangIn (sdk).getFullPathName());
        args.add ("--target=wasm32-wasip1");
        args.add ("--sysroot=" + sdk.getChildFile ("share").getChildFile ("wasi-sysroot").getFullPathName());
        args.addArray ({ "-O2", "-std=c++17", "-fno-exceptions", "-fno-rtti", "-Wall" });
        return args;
    };

    auto run = [] (const juce::StringArray& args, juce::String& log, int timeoutMs)
    {
        juce::ChildProcess clang;

        if (! clang.start (args, juce::ChildProcess::wantStdOut | juce::ChildProcess::wantStdErr))
        {
            log = "The plugin compiler couldn't be started.";
            return false;
        }

        log = clang.readAllProcessOutput();
        clang.waitForProcessToFinish (timeoutMs);
        return clang.getExitCode() == 0;
    };

    // The runtime (drawing, text, the font) is compiled once per studio version and kept.
    const auto object = runtime.getChildFile ("runtime-" + elementRuntimeKey() + ".o");

    if (! object.existsAsFile())
    {
        if (! writeElementRuntime (runtime))
        {
            result.log = "Couldn't write into the build folder " + runtime.getFullPathName();
            return result;
        }

        const auto partial = runtime.getChildFile ("runtime-building.o");
        auto args = baseArgs();
        args.add ("-I" + runtime.getFullPathName());
        args.add ("-c");
        args.add (runtime.getChildFile ("stella_elements.cpp").getFullPathName());
        args.add ("-o");
        args.add (partial.getFullPathName());

        juce::String log;

        if (! run (args, log, 120000) || ! partial.existsAsFile() || ! partial.moveFileTo (object))
        {
            result.log = "The GUI elements' runtime didn't compile:\n" + log.trim();
            return result;
        }
    }
    else
    {
        writeElementRuntime (runtime);   // the headers, should they have been cleared away
    }

    const auto output = work.getChildFile ("elements.wasm");
    output.deleteFile();

    auto args = baseArgs();
    args.add ("-mexec-model=reactor");
    args.add ("-I" + runtime.getFullPathName());
    args.add ("-I" + elements.getFullPathName());
    args.add ("-o");
    args.add (output.getFullPathName());
    args.add (object.getFullPathName());

    for (const auto& file : files)
        args.add (file.getFullPathName());

    args.add ("-Wl,--strip-all");

    juce::String log;
    const bool linked = run (args, log, 60000);

    result.log = log.replace (elements.getFullPathName() + juce::File::getSeparatorString(), juce::String (elementsFolderName) + "/")
                    .replace (runtime.getFullPathName() + juce::File::getSeparatorString(), "")
                    .trim();
    result.ok = linked && output.existsAsFile();
    result.wasm = result.ok ? output : juce::File();
    result.seconds = (juce::Time::getMillisecondCounterHiRes() - started) / 1000.0;

    if (! result.ok && result.log.isEmpty())
        result.log = "The GUI elements' compiler stopped without saying why.";

    return result;
}

//==============================================================================
WasmCompiler::Result WasmCompiler::compile (const juce::File& projectFolder, const juce::String& projectId)
{
    Result result;
    const auto started = juce::Time::getMillisecondCounterHiRes();

    const auto sdk = findCompiler();

    if (sdk == juce::File())
    {
        result.log = "The plugin compiler that comes with Stella AI Studio is missing. Reinstall the studio.";
        return result;
    }

    // The work folder is the studio's own, outside the project: the project stays clean.
    const auto work = juce::File::getSpecialLocation (juce::File::tempDirectory)
                          .getChildFile ("Stella AI Studio")
                          .getChildFile ("build-" + juce::File::createLegalFileName (projectId));

    if (! work.isDirectory() && ! work.createDirectory())
    {
        result.log = "Couldn't create the build folder " + work.getFullPathName();
        return result;
    }

    juce::String graphSource;

    if (const auto graph = generateGraphSource (projectFolder.getChildFile (graphFileName), graphSource); graph.failed())
    {
        result.log = graph.getErrorMessage();
        return result;
    }

    const auto output = work.getChildFile ("plugin.wasm");
    output.deleteFile();

    if (! writeRuntime (work) || ! work.getChildFile ("stella_graph.cpp").replaceWithText (graphSource))
    {
        result.log = "Couldn't write into the build folder " + work.getFullPathName();
        return result;
    }

    const auto modules = projectFolder.getChildFile ("modules");
    auto moduleFiles = modules.findChildFiles (juce::File::findFiles, false, "*.cpp");
    moduleFiles.sort();

    juce::StringArray args;
    args.add (clangIn (sdk).getFullPathName());
    args.add ("--target=wasm32-wasip1");
    args.add ("--sysroot=" + sdk.getChildFile ("share").getChildFile ("wasi-sysroot").getFullPathName());
    args.addArray ({ "-O2", "-std=c++17", "-fno-exceptions", "-fno-rtti", "-mexec-model=reactor", "-Wall" });
    args.add ("-I" + work.getFullPathName());
    args.add ("-I" + modules.getFullPathName());
    args.add ("-o");
    args.add (output.getFullPathName());
    args.add (work.getChildFile ("stella_runtime.cpp").getFullPathName());
    args.add (work.getChildFile ("stella_graph.cpp").getFullPathName());

    for (const auto& file : moduleFiles)
        args.add (file.getFullPathName());

    args.add ("-Wl,--strip-all");

    juce::ChildProcess clang;

    if (! clang.start (args, juce::ChildProcess::wantStdOut | juce::ChildProcess::wantStdErr))
    {
        result.log = "The plugin compiler couldn't be started.";
        return result;
    }

    auto log = clang.readAllProcessOutput();
    clang.waitForProcessToFinish (5000);

    // Shorter messages: "modules/LowPass.cpp:12:3: error ..." rather than full paths.
    log = log.replace (modules.getFullPathName() + juce::File::getSeparatorString(), "modules/")
             .replace (work.getFullPathName() + juce::File::getSeparatorString(), "")
             .trim();

    result.log = log;
    result.ok = clang.getExitCode() == 0 && output.existsAsFile();
    result.wasm = result.ok ? output : juce::File();
    result.seconds = (juce::Time::getMillisecondCounterHiRes() - started) / 1000.0;

    if (! result.ok && result.log.isEmpty())
        result.log = "The plugin compiler stopped without saying why.";

    return result;
}
